// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiContextIssue.Contexts;

#nullable disable

namespace MultiContextIssue.Migrations.AnotherSchool
{
    [DbContext(typeof(AnotherSchoolContext))]
    partial class AnotherSchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("anos")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MultiContextIssue.Models.OtherCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OtherStudentStudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("OtherStudentStudentId");

                    b.ToTable("OtherCourses", "anos");
                });

            modelBuilder.Entity("MultiContextIssue.Models.OtherStudent", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("OtherStudents", "anos");
                });

            modelBuilder.Entity("MultiContextIssue.Models.OtherCourse", b =>
                {
                    b.HasOne("MultiContextIssue.Models.OtherStudent", null)
                        .WithMany("OtherCourses")
                        .HasForeignKey("OtherStudentStudentId");
                });

            modelBuilder.Entity("MultiContextIssue.Models.OtherStudent", b =>
                {
                    b.Navigation("OtherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
